### ISSUE TITLE
Prometheus remote write

### ISSUE THREAD

**Issue by nlamirault** [aws-observability/aws-otel-helm-charts#11]
Hi, how can i specify the configuration for Prometheus Remote Write ?
Like here : https://github.com/aws-samples/amazon-eks-observability-demo/blob/main/observability/resources/adot-configmap.yaml

```yaml
adot-collector-config: |
    
    exporters:
      awsprometheusremotewrite:
        # replace this with your endpoint
        endpoint: "${APS_REMOTE_WRITE_ENDPOINT}"
        # replace this with your region
        aws_auth:
          region: "${APS_REGION}"
          service: "aps"
        namespace: "adot"
      awsxray:
          region: "${AWS_REGION}"
      logging:
        loglevel: debug
    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [awsxray]
        metrics:
          receivers: [prometheus]
          exporters: [logging, awsprometheusremotewrite]
```
