### ISSUE TITLE
The default pod attributes (e.g. env, volumes) should be declared in templates, not in values file

### ISSUE THREAD

**Issue by cazorla19** [aws-observability/aws-otel-helm-charts#110]
**Describe the bug**

Those pod attributes that otel-exporter definitely needs to function, such as `env`, `volume`, `command` and so on, won't need to be set by values, rather being placed directly in `templates/` directory.

The current approach is not convenient, when you want to set your own environment variable, such as AWS SDK Credentials for example, and with that you have to list in your values file all other environmnent variables declared in default values file - otherwise, they will be gone. Same thing with volumes. Generally, there is an idea that values file can be shorter and such inconveniences will be avoided.

My proposal is to:

1. `env`, `volume`, `command` and other default attributes from `values.yaml` to `templates`, for both daemonset and sidecar.

**Steps to reproduce**

```
    containersName: "adot-collector-container"
    env:
      - name: "AWS_REGION"
        valueFrom:
          secretKeyRef:
            name: "adot-aws-credentials"
            key: "AWS_REGION"
      - name: "AWS_ACCESS_KEY_ID"
        valueFrom:
          secretKeyRef:
            name: "adot-aws-credentials"
            key: "AWS_ACCESS_KEY_ID"
      - name: "AWS_SECRET_ACCESS_KEY"
        valueFrom:
          secretKeyRef:
            name: "adot-aws-credentials"
            key: "AWS_SECRET_ACCESS_KEY"
    command: ...
```

```
helm install -n [NAMESPACE_NAME] [RELEASE_NAME] [REPO_NAME]/adot-exporter-for-eks-on-ec2

helm install -n monitoring adot aws-otel/adot-exporter-for-eks-on-ec2
```

**What did you expect to see?**

Declared variables set for daemonset/sidecar altogether with default variables, such as `K8S_POD_NAME`

**What did you see instead?**

All default variables are gone.

**Environment**

This issue is environment-agnostic

**Additional context**

I'm willing to fix it by forking the chart and sending the PR for my proposal. Please let me know what you think about this issue.
