### ISSUE TITLE
ADOT Collector ignores prometheus.io port annotation

### ISSUE THREAD

**Issue by dpattmann** [aws-observability/aws-otel-helm-charts#37]
While I tried to use the ADOT Collector to scrape metrics from the prometheus /metric endpoint, I recognized that the config ignores the prometheus.io/port pod annotation.

I fixed it by updating the `ampreceivers.scrapeConfigs` configuration

from

```yaml
  - source_labels: [__address__]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $$1:$$2
    target_label: __address__
```
to
```yaml
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $$1:$$2
    target_label: __address__
```
