### ISSUE TITLE
feat: Support multiple ADOT pipelines via helm chart

### ISSUE THREAD

**Issue by dpattmann** [aws-observability/aws-otel-helm-charts#53]
Hi,

I would like to suggest a new feature (multi pipeline support) for the helm chart.

Currently only one pipeline is supported by the ADOT configuration. I have a use case, where I would like to write some metrics to Prometheus and some metrics to Cloudwatch.

A configuration like this would be a solution.

```
data:
  adot-config:  |
    extensions:
      health_check:
    ...
    service:
      pipelines:
        metrics/prometheus:
          receivers:
          - prometheus
          processors:
          - batch/metrics
          exporters:
          - awsprometheusremotewrite
        metrics/cloudwatch:
          receivers:
          - awscontainerinsightreceiver
          processors:
          - batch/metrics
          exporters:
          - awsemf
```

However, currently there is no possibiliaty to configure the service like that.
