### ISSUE TITLE
log retention days is not working

### ISSUE THREAD

**Issue by xpicio** [aws-observability/aws-otel-helm-charts#69]
**Describe the bug**
Setting the following properties of `log_retention` to `true` and `60` the retention days on CloudWatch console is still set to `Never Expire`
```
fluentbit:
  enabled: true
  image:
    tag: 2.28.1
  output:
    applicationLog:
      log_retention:
        enabled: true
        days: 60
    dataplaneLog:
      log_retention:
        enabled: true
        days: 60
    hostLog:
      log_retention:
        enabled: true
        days: 60
```

**What did you expect to see?**
<img width="1406" alt="Schermata 2022-09-27 alle 18 32 11" src="https://user-images.githubusercontent.com/2994719/192583446-66721b7a-8b44-4d2a-93c7-71c888447e8c.png">

**What did you see instead?**
![error](https://user-images.githubusercontent.com/2994719/192584344-2207710f-b14a-4b71-b5e5-2467c80da8a0.jpg)

**Environment**
kubernets 1.23
fluentbit 2.28.1 (i tried with 2.21.1 with the same result)
aws-otel-helm-charts 0.7.0

Have a nice day
