### ISSUE TITLE
ENHANCEMENT: Enable cloudwatch log group retention for adot-collector metrics performance log

### ISSUE THREAD

**Issue by jennerm** [aws-observability/aws-otel-helm-charts#87]
Hi Team, 

Enhancement https://github.com/aws-observability/aws-otel-helm-charts/issues/23 enabled cloudwatch log group retention for:
- application
- dataplane
- host

But it did not enable it for the `performance` log which is used by the adot-collector for the metrics.  I think it needs to be added to the `adot-config` data in the adot-collector `ConfigMap`, something like:

```
    exporters:
      awsemf:
        namespace: {{ .Values.adotCollector.daemonSet.cwexporters.namespace }}
        log_group_name: '/aws/containerinsights/{{ .Values.clusterName }}/performance'
        log_stream_name: {{ .Values.adotCollector.daemonSet.cwexporters.logStreamName }}
        log_retention: 60
```
As described on this page: https://aws-otel.github.io/docs/getting-started/cloudwatch-metrics

It would be great if the Helm chart could be updated with this extra option.
Thanks
